import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const src=fs.readFileSync(new URL("../src/index.ts",import.meta.url),"utf8");
const rich=fs.readFileSync(new URL("../public/richtext.js",import.meta.url),"utf8");
test("secure cookie controls",()=>assert.match(src,/HttpOnly; Secure; SameSite=Strict/));
test("PBKDF2 SHA-256",()=>{assert.match(src,/PBKDF2/);assert.match(src,/210000/);assert.match(src,/SHA-256/)});
test("same-origin state changes",()=>assert.match(src,/origin===new URL\(req\.url\)\.origin/));
test("tenant-scoped memos",()=>assert.match(src,/WHERE m\.organization_id=\?/));
test("administrator enforcement",()=>assert.match(src,/u\.role!=="admin"/));
test("password reset revokes sessions",()=>assert.match(src,/DELETE FROM sessions WHERE user_id=\?/));
test("notifications are tenant and user scoped",()=>assert.match(src,/WHERE organization_id=\? AND user_id=\?/));
test("attachments enforce size and type",()=>{assert.match(src,/750000/);assert.match(src,/allowed\.has\(file\.type\)/)});
test("delegation requires active bounded period",()=>{assert.match(src,/d\.status='active'/);assert.match(src,/d\.start_at<=\?/);assert.match(src,/d\.end_at>=\?/)});
test("reports require organization scope",()=>{assert.match(src,/\/api\/v2\/admin\/reports/);assert.match(src,/m\.organization_id=\?/)});
test("branding accepts HTTPS logos only",()=>assert.match(src,/parsed\.protocol!=="https:"/));
test("rich text escapes input",()=>assert.match(rich,/let s=e\(value\)/));
