interface Env{DB:D1Database;ASSETS:Fetcher;APP_NAME:string;SESSION_HOURS:string;RESEND_API_KEY?:string;RESET_FROM_EMAIL?:string}
type User={id:string;organization_id:string;organization_name:string;name:string;email:string;role:"admin"|"user";status:string};
const enc=new TextEncoder();
const json=(data:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}});
const b64=(a:ArrayBuffer|Uint8Array)=>{let s="";for(const b of new Uint8Array(a))s+=String.fromCharCode(b);return btoa(s)};
const unb64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const random=(n=32)=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return b64(a).replace(/[+/=]/g,"")};
async function sha(v:string){return b64(await crypto.subtle.digest("SHA-256",enc.encode(v)))}
async function hashPassword(password:string,salt=random(18),iterations=100000){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:typeof salt==="string"?enc.encode(salt):salt,iterations},key,256);return `pbkdf2_sha256$${iterations}$${b64(enc.encode(salt))}$${b64(bits)}`}
async function verifyPassword(password:string,stored:string){try{const[,i,s,h]=stored.split("$");const salt=new TextDecoder().decode(unb64(s));const actual=(await hashPassword(password,salt,Number(i))).split("$")[3];const a=unb64(actual),b=unb64(h);if(a.length!==b.length)return false;let d=0;for(let x=0;x<a.length;x++)d|=a[x]^b[x];return d===0}catch{return false}}
function cookie(req:Request,name:string){return req.headers.get("cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith(name+"="))?.slice(name.length+1)}
function sessionCookie(value:string,maxAge:number){return `mf_session=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`}
function validOrigin(req:Request){if(["GET","HEAD","OPTIONS"].includes(req.method))return true;const origin=req.headers.get("origin");return !origin||origin===new URL(req.url).origin}
async function currentUser(req:Request,env:Env):Promise<User|null>{const token=cookie(req,"mf_session");if(!token)return null;const row=await env.DB.prepare(`SELECT u.id,u.organization_id,o.name organization_name,u.name,u.email,u.role,u.status FROM sessions s JOIN users u ON u.id=s.user_id JOIN organizations o ON o.id=u.organization_id WHERE s.id_hash=? AND s.expires_at>? AND u.status='active'`).bind(await sha(token),new Date().toISOString()).first<User>();return row||null}
async function audit(env:Env,u:User,type:string,entity:string|null,desc:string){await env.DB.prepare("INSERT INTO audit_logs(id,organization_id,user_id,event_type,entity_type,entity_id,description,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),u.organization_id,u.id,type,entity?"user":null,entity,desc,new Date().toISOString()).run()}
async function body(req:Request){try{return await req.json() as Record<string,string>}catch{return {}}}
function passwordOK(p:string){return p.length>=12&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/[0-9]/.test(p)&&/[^A-Za-z0-9]/.test(p)}

async function api(req:Request,env:Env,path:string){
 if(!validOrigin(req))return json({error:"Invalid request origin."},403);
 if(path==="/api/login"&&req.method==="POST"){const b=await body(req);const email=(b.email||"").trim().toLowerCase();const row=await env.DB.prepare(`SELECT u.id,u.organization_id,o.name organization_name,u.name,u.email,u.password_hash,u.role,u.status FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.email=? AND u.status='active'`).bind(email).first<User&{password_hash:string}>();if(!row||!await verifyPassword(b.password||"",row.password_hash))return json({error:"Invalid email or password."},401);const token=random(36),now=new Date(),expires=new Date(now.getTime()+Number(env.SESSION_HOURS||12)*3600000);await env.DB.prepare("INSERT INTO sessions(id_hash,user_id,organization_id,expires_at,created_at,last_seen_at,user_agent) VALUES(?,?,?,?,?,?,?)").bind(await sha(token),row.id,row.organization_id,expires.toISOString(),now.toISOString(),now.toISOString(),req.headers.get("user-agent")).run();await audit(env,row,"USER_LOGIN",row.id,"Successful login");return json({user:{id:row.id,name:row.name,email:row.email,role:row.role,organization:row.organization_name}},200,{"set-cookie":sessionCookie(token,Number(env.SESSION_HOURS||12)*3600)})}
 if(path==="/api/logout"&&req.method==="POST"){const token=cookie(req,"mf_session");if(token)await env.DB.prepare("DELETE FROM sessions WHERE id_hash=?").bind(await sha(token)).run();return json({ok:true},200,{"set-cookie":sessionCookie("",0)})}
 if(path==="/api/forgot-password"&&req.method==="POST"){const b=await body(req);const row=await env.DB.prepare("SELECT id,email FROM users WHERE email=? AND status='active'").bind((b.email||"").trim().toLowerCase()).first<{id:string,email:string}>();let demoToken:string|undefined;if(row){const token=random(36);await env.DB.prepare("DELETE FROM password_resets WHERE user_id=?").bind(row.id).run();await env.DB.prepare("INSERT INTO password_resets(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(await sha(token),row.id,new Date(Date.now()+30*60000).toISOString(),new Date().toISOString()).run();if(env.RESEND_API_KEY&&env.RESET_FROM_EMAIL){await fetch("https://api.resend.com/emails",{method:"POST",headers:{"authorization":`Bearer ${env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:env.RESET_FROM_EMAIL,to:[row.email],subject:"MemoFlow password reset",html:`<p>Reset your password: <a href="${new URL(req.url).origin}/?reset=${encodeURIComponent(token)}">Reset password</a>. This link expires in 30 minutes.</p>`})})}else demoToken=token}return json({message:"If that account exists, reset instructions have been created.",demoToken})}
 if(path==="/api/reset-password"&&req.method==="POST"){const b=await body(req);if(!passwordOK(b.password||""))return json({error:"Use 12+ characters with upper, lower, number and symbol."},400);const tokenHash=await sha(b.token||"");const reset=await env.DB.prepare("SELECT user_id FROM password_resets WHERE token_hash=? AND used_at IS NULL AND expires_at>?").bind(tokenHash,new Date().toISOString()).first<{user_id:string}>();if(!reset)return json({error:"Reset link is invalid or expired."},400);const now=new Date().toISOString();await env.DB.batch([env.DB.prepare("UPDATE users SET password_hash=?,updated_at=? WHERE id=?").bind(await hashPassword(b.password),now,reset.user_id),env.DB.prepare("UPDATE password_resets SET used_at=? WHERE token_hash=?").bind(now,tokenHash),env.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(reset.user_id)]);return json({message:"Password changed. Please sign in."})}
 const u=await currentUser(req,env);if(!u)return json({error:"Authentication required."},401);
 if(path==="/api/me")return json({user:{...u,password_hash:undefined}});
 if(path==="/api/memos"&&req.method==="GET"){const rows=await env.DB.prepare(`SELECT m.id,m.reference_no,m.subject,m.status,m.priority,m.created_at,u.name author FROM memos m JOIN users u ON u.id=m.author_id WHERE m.organization_id=? ORDER BY m.created_at DESC`).bind(u.organization_id).all();return json({memos:rows.results})}
 if(path==="/api/memos"&&req.method==="POST"){const b=await body(req);if(!b.subject?.trim()||!b.body?.trim())return json({error:"Subject and body are required."},400);const count=await env.DB.prepare("SELECT COUNT(*) n FROM memos WHERE organization_id=?").bind(u.organization_id).first<{n:number}>();const ref=`MEM-${new Date().getUTCFullYear()}-${String((count?.n||0)+1).padStart(4,"0")}`,id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO memos(id,organization_id,author_id,department_id,reference_no,subject,body,status,priority,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(id,u.organization_id,u.id,null,ref,b.subject.trim(),b.body.trim(),b.status==="Draft"?"Draft":"Pending Approval",["Normal","High","Urgent"].includes(b.priority)?b.priority:"Normal",now,now).run();await audit(env,u,"MEMO_CREATED",id,`${ref} created`);return json({id,reference_no:ref},201)}
 if(path==="/api/admin/users"&&req.method==="GET"){if(u.role!=="admin")return json({error:"Administrator authority required."},403);const rows=await env.DB.prepare("SELECT id,name,email,role,status,created_at FROM users WHERE organization_id=? ORDER BY name").bind(u.organization_id).all();return json({users:rows.results})}
 if(path==="/api/admin/users"&&req.method==="POST"){if(u.role!=="admin")return json({error:"Administrator authority required."},403);const b=await body(req);if(!b.name||!b.email||!passwordOK(b.password||""))return json({error:"Name, email and a strong password are required."},400);const id=crypto.randomUUID(),now=new Date().toISOString();try{await env.DB.prepare("INSERT INTO users(id,organization_id,department_id,name,email,password_hash,role,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,u.organization_id,null,b.name.trim(),b.email.trim().toLowerCase(),await hashPassword(b.password),b.role==="admin"?"admin":"user","active",now,now).run();await audit(env,u,"USER_CREATED",id,`${b.email} created as ${b.role==="admin"?"admin":"user"}`);return json({id},201)}catch{return json({error:"A user with that email already exists in this organization."},409)}}
 if(path==="/api/audit"&&req.method==="GET"){if(u.role!=="admin")return json({error:"Administrator authority required."},403);const rows=await env.DB.prepare("SELECT event_type,description,created_at,user_id FROM audit_logs WHERE organization_id=? ORDER BY created_at DESC LIMIT 50").bind(u.organization_id).all();return json({events:rows.results})}
 return json({error:"Not found."},404)
}
export default{async fetch(req:Request,env:Env){const url=new URL(req.url);if(url.pathname.startsWith("/api/"))return api(req,env,url.pathname);return env.ASSETS.fetch(req)}};
export{hashPassword,verifyPassword,passwordOK};
